akaihola/darker

CHANGES.rst, CONTRIBUTORS.rst, src/darker/__main__.py, src/darker/black_diff.py, src/darker/command_line.py, src/darker/tests/test_black_diff.py
Hi!
Now darker can use the black config.
It's ugly because it uses a dirty hack with click module. This was done for reusing purposes of the black code.
=> Add support for black config

src/darker/__main__.py, src/darker/git_diff.py, src/darker/tests/test_git_diff.py, src/darker/utils.py
Having only file mode changes compared to the last commit would crash `darker`. That has been fixed in this pull request.
=> Git diff mode change fix

CHANGES.rst, pytest.ini, setup.cfg, src/darker/__main__.py, src/darker/import_sorting.py, src/darker/tests/test_main.py
=> Add support of isort>5

src/darker/import_sorting.py, src/darker/tests/test_main.py
This gets rid of unnecessary isort check errors on stdout.
=> Remove `isort.check_code()` call

pytest.ini, setup.cfg
=> Bump `pytest-isort` version to `1.1.0`

src/darker/__main__.py, src/darker/diff.py, src/darker/tests/test_diff.py
When `git diff` was replaced with `difflib.SequenceMatcher` in #11, I failed to also re-implement "context expansion". The equivalent of `git diff -U<number-of-context-lines>` is now properly implemented in `diff_and_get_opcodes()` again. Additionally, the number of extra context lines can no longer grow beyond the number of lines in the processed file.
What context expansion does is:
In case the AST of the original edited file doesn't match with the AST of the partially reformatted one, darker considers one more line before and after every user-edited chunk as part of the chunk. This expansion is repeated one line at a time until the ASTs match.
Context expansion helps is rare cases of two nearby chunks of Black reformatting separated by intact lines. Sometimes applying only one of those …
=> Context extension fix

CHANGES.rst, pyproject.toml, setup.cfg, src/darker/__main__.py, src/darker/black_diff.py, src/darker/import_sorting.py, src/darker/tests/test_black_diff.py, src/darker/tests/test_import_sorting.py, src/darker/tests/test_main.py
Attempt # 2. Decided to rewrite #13 from scratch after #16 due to a lot of conflicts and redundant code
@akaihola your comments from #13 were taken to account:
- TypedDict for BlackArgs / IsortArgs
- debug message is readable enough
=> Allow to configure `isort` through `pyproject.toml`

CHANGES.rst
The version number headers in `CHANGES.rst` now link to the GitHub URL with the list of commits since the previous release. These links have three periods between version numbers (e.g. `0.2.0...1.0.0`) instead of just two periods (e.g. `0.2.0..1.0.0`) which link to a diff between versions instead. The commit log is certainly more useful.
=> Changelog to link to commit logs, not diffs

src/darker/__main__.py, src/darker/command_line.py
This fixes annoying:
```
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/mm/.virtualenvs/black/lib/python3.8/site-packages/darker/__main__.py", line 191, in <module>
main()
File "/home/mm/.virtualenvs/black/lib/python3.8/site-packages/darker/__main__.py", line 187, in main
format_edited_parts(paths, args.isort, black_args, args.diff)
File "/home/mm/.virtualenvs/black/lib/python3.8/site-packages/darker/__main__.py", line 52, in format_edited_parts
git_root = get_common_root(srcs)
File "/home/mm/.virtualenvs/black/lib/python3.8/site-packages/darker/utils.py", line 51, in get_common_root
raise …
```
=> Don't show traceback if there are no SRCs specified

src/darker/black_diff.py, src/darker/tests/test_command_line.py
A new version of Mypy seems to be stricter and introduced new type checking failures. This patch should fix them.
=> Fix failures with updated Mypy

CHANGES.rst, README.rst, src/darker/__main__.py, src/darker/command_line.py, src/darker/tests/test_command_line.py, src/darker/tests/test_main.py, src/darker/version.py
`--check` skips writing changes to files, and returns a return value of 1 from the `darker` process in case any modified lines in any of the given files are not already properly formatted.
The return value will allow using `darker` with more different tools. It for example opens the possibility for a `pytest-darker` plugin.
=> `--check` option, mirroring `black --check`

CHANGES.rst, src/darker/__main__.py, src/darker/tests/test_main.py
This is now similar to `black --diff`.
Fixes #34.
=> Paths from `--diff` now relative to workdir (#34)

CHANGES.rst, src/darker/__main__.py, src/darker/git.py, src/darker/tests/test_git.py
`git diff --name-only` didn't include newly created untracked files so they were not included in reformatting. A call to `git ls-files` with suitable arguments is now made in addition so untracked files will be included.
=> Reformat newly added files, too

CHANGES.rst, README.rst, src/darker/__main__.py, src/darker/command_line.py, src/darker/tests/conftest.py, src/darker/tests/test_command_line.py
This option can be used to override
```toml
[tool.black]
skip-string-normalization = true
```
from `pyproject.toml` (or another configuration file used via the `--config` option).
=> `--no-skip-string-normalization` option

CHANGES.rst, README.rst, setup.cfg, src/darker/__main__.py, src/darker/command_line.py, src/darker/git.py, src/darker/tests/conftest.py, src/darker/tests/test_command_line.py, src/darker/tests/test_git.py, src/darker/tests/test_main.py, src/darker/tests/test_main_revision.py
Fixes #42. Should be reviewed and merged only after #48 has been merged.
TODO: unit tests
=> WIP: Add -r / --revision argument for specifying which Git revision to compare to

CHANGES.rst, README.rst, src/darker/__main__.py, src/darker/command_line.py, src/darker/git.py, src/darker/linting.py, src/darker/tests/test_command_line.py, src/darker/tests/test_git.py, src/darker/tests/test_linting.py, src/darker/tests/test_main.py
In addition to Black and Isort, darker gains here the ability to run a linter or linters, and only output linting errors/warnings for edited lines.
This has been tested with
- Pylint (`-L pylint`; requires an upcoming Pylint release with Isort 5 support)
- Mypy (`-L mypy`)
- Flake8 (`-L flake8`)
Probably others work as well – this only depends on the error/warning lines in the output to be in one of the following formats:
- `<path>:<linenum>: <description>`
- `<path>:<linenum>:<column>: <description>`
=> Add support for linters

src/darker/__main__.py, src/darker/git.py, src/darker/linting.py, src/darker/tests/test_git.py, src/darker/tests/test_linting.py
When rebasing linter support in #33, I missed the need to pass the `-r` / `--revision` option there, too.
With this patch, linter output is now filtered correctly by comparing the working tree against the given revision, instead of against `HEAD`.
Could you @Carreau or @samoylovfp take a look at this quick fix?
=> Bugfix: Linter support to diff against given revision

.travis.yml, CHANGES.rst, mypy.ini, pyproject.toml, pytest.ini, setup.cfg, src/darker/__main__.py, src/darker/argparse_helpers.py, src/darker/black_diff.py, src/darker/command_line.py, src/darker/config.py, src/darker/linting.py, src/darker/tests/conftest.py, src/darker/tests/helpers.py, src/darker/tests/test_argparse_helpers.py, src/darker/tests/test_command_line.py, src/darker/tests/test_config.py, src/darker/tests/test_diff.py, src/darker/tests/test_linting.py
Also dumps configuration on terminal if debug level logging is enabled with the `-vv` or `--verbose --verbose` command line option.
=> Read configuration from pyproject.toml

CHANGES.rst, README.rst, src/darker/command_line.py, src/darker/git.py, src/darker/tests/test_git.py
This is useful for comparing to the best common ancestor, e.g. `master...`.
I noticed the need for this when I had merges and other commits in `master` after the branch point from which the checked branch started. Without a range, code removed in `master` would get reformatted in the branch.
=> Support commit ranges for `-r` / `--revision`

CHANGES.rst, README.rst, src/darker/version.py
- Configuration for Darker can now be done in ``pyproject.toml``.
- The formatting of the Darker code base itself is now checked using Darker itself and pytest-darker. Currently the formatting is a mix of Black 19.10 and Black 20.8 rules, and Travis CI only requires Black 20.8 formatting for lines modified in merge requests. In a way, Darker is now eating its own dogfood.
- Support commit ranges for `-r`/`--revision`. Useful for comparing to the best common ancestor, e.g. `master...`.
- Configure Flake8 verification for Darker's own source code
=> Release version 1.2.0

CHANGES.rst, README.rst
Also point out in a more clear way that the path arguments can be both files and directories.
=> Improve example in README

setup.cfg, src/darker/tests/helpers.py, src/darker/tests/test_argparse_helpers.py, src/darker/tests/test_command_line.py, src/darker/tests/test_main_revision.py
Some parameterized tests have both values and exceptions as expected outcomes. With recent Pytest and Mypy versions, the type of the conditional context manager doesn't check when written using Python's ternary operator. We get these errors when Pytest runs Mypy checks for Darker:
```python
__________________ src/darker/tests/test_argparse_helpers.py ___________________
33: error: "object" has no attribute "__enter__"
33: error: "object" has no attribute "__exit__"
____________________ src/darker/tests/test_command_line.py _____________________
31: error: "object" has no attribute "__enter__"
31: error: "object" has no attribute "__exit__"
86: error: "object" has no attribute "__enter__"
86: error: "object" has no attribute "__exit__"
____________________ …
```
=> Refactor conditional raise assertion in tests

src/darker/tests/conftest.py
These two additional methods in `darker.tests.conftest.GitRepoFixture` will be needed in unit tests in #80.
=> Add GitRepoFixture helper methods needed by #80

.pre-commit-hooks.yaml, CHANGES.rst, README.rst
This is #2 rebased on top of `master` as of 2020-11-26.
=> Add ability to use as a pre-commit hook

README.rst, setup.cfg, setup.py
PyPI doesn't allow raw HTML in the README. Strip it out before creating distribution archives.
Raw HTML is used for the contributors table to be displayed on GitHub.
To verify that this works correctly, you can do the following:
```bash
pip install wheel twine
rm dist/*.whl dist/*.tar.gz
python setup.py sdist ; python setup.py bdist_wheel ; twine check dist/*
```
For more information, see [Validating reStructuredText markup](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup) in the [Making a PyPI-friendly README](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup) section of the [Python Packaging User Guide](https://packaging.python.org/).
=> Strip raw HTML from `README.rst` when packaging

CHANGES.rst, README.rst, src/darker/version.py
Added
-----
- Travis CI now runs [Pylint](https://pypi.org/project/pylint) on modified lines via [pytest-darker](https://pypi.org/project/pytest-darker/)
- Darker can now be used as a pre-commit hook (see [pre-commit](https://pre-commit.com/))
- Document integration with Vim
- Thank all contributors right in the `README`
- `RevisionRange` class and Git repository test fixture improvements in preparation for a larger refactoring coming in #80
Fixed
-----
- Improve example in `README` and clarify that path argument can also be a directory
=> Release version 1.2.1. Fixes #100.

.travis.yml
With old pip we got:
```bash
$ pip install -e '.[isort,test]'
[...]
Collecting pytest-mypy; extra == "test"
Using cached pytest_mypy-0.8.0-py3-none-any.whl (6.6 kB)
Collecting pytest>=6.1.0; extra == "test"
Downloading pytest-6.2.1-py3-none-any.whl (279 kB)
[...]
Requirement already satisfied: attrs>=19.0 in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from pytest-mypy; extra == "test"->darker==1.2.2.dev0) (19.1.0)
[...]
ERROR: pytest 6.2.1 has requirement attrs>=19.2.0, but you'll have attrs 19.1.0 which is incompatible.
[...]
Successfully installed appdirs-1.4.4 astroid-2.4.2 black-20.8b1 click-7.1.2 darker filelock-3.0.12 flake8-3.8.4 iniconfig-1.1.1 isort-5.6.4 lazy-object-proxy-1.4.3 mccabe-0.6.1 mypy-0.790 mypy-extensions-0.4.3 pathspec-0.8.1 py-1.10.0 …
```
=> Use new pip to solve pytest/attrs version conflict

CHANGES.rst, pyproject.toml, src/darker/__main__.py, src/darker/git.py, src/darker/linting.py, src/darker/tests/test_command_line.py, src/darker/tests/test_git.py, src/darker/tests/test_linting.py, src/darker/tests/test_main.py
Bugfix: `<commit>...` now compares always correctly to the latest common ancestor
This merge request used to be even larger, but I've managed to trim it down. I hope someone is willing to review it in one go.
**Note:** #107 will fix the build failure.
=> Common ancestor fix

.pre-commit-hooks.yaml, CHANGES.rst, README.rst, src/darker/command_line.py, src/darker/git.py, src/darker/tests/test_git.py
When using the `-r :PRE-COMMIT:` / `--revision=:PRE-COMMIT:` parameter, Darker will expect to find the revision range from the `PRE_COMMIT_FROM_REF` and `PRE_COMMIT_TO_REF` environment variables as set by `pre-commit`.
Based on #108, should be merged after that one.
=> Get revision range from pre-commit environment variables

src/darker/__main__.py, src/darker/black_diff.py, src/darker/chooser.py, src/darker/diff.py, src/darker/git.py, src/darker/import_sorting.py, src/darker/tests/test_black_diff.py, src/darker/tests/test_chooser.py, src/darker/tests/test_command_line.py, src/darker/tests/test_diff.py, src/darker/tests/test_git.py, src/darker/tests/test_import_sorting.py, src/darker/tests/test_linting.py, src/darker/tests/test_main.py, src/darker/tests/test_utils.py, src/darker/tests/test_verification.py, src/darker/utils.py, src/darker/verification.py
We used to handle text documents either as strings or as lists of strings, or both, depending on in which format various 3rd party libraries needed them.
To simplify things, a `TextDocument` class has now been created. It automatically provides the contents of a document both in a string and a tuple of strings format. The objects are immutable, and tuples are used to achieve immutability of the text line collections.
=> Unified text document class

src/darker/black_diff.py, src/darker/command_line.py, src/darker/import_sorting.py, src/darker/tests/test_main.py
MyPy strict mode now disallows implicit re-export.
See https://github.com/tiangolo/typer/issues/112#issuecomment-648344361
=> Satisfy MyPy 0.812 using `__all__`

src/darker/tests/test_utils.py, src/darker/utils.py, src/darker/verification.py
The function dumps debug output whenever AST verification fails.
- drop unused arguments
- only print the dump if the `-vv` option has been specified
=> Clean up the `debug_dump()` function

CHANGES.rst, src/darker/command_line.py, src/darker/git.py, src/darker/tests/test_git.py
Improve compatibility with `pre-commit` by falling back to comparing against HEAD, when running in `:PRE-COMMIT:` mode and the relevant environment variables are not set.
Resolves #113
=> Improve compatibility with `pre-commit`

src/darker/black_diff.py, src/darker/diff.py, src/darker/tests/conftest.py, src/darker/tests/test_command_line.py, src/darker/tests/test_git.py, src/darker/tests/test_linting.py, src/darker/tests/test_main.py, src/darker/tests/test_main_revision.py, src/darker/tests/test_utils.py
This branch sits on top of #120 since we want to see the test result of Windows. Once we see that this fix works, let's rebase this on `master` and merge before merging #120.
=> newline-unit-test-fix

CHANGES.rst, src/darker/__main__.py, src/darker/tests/test_main.py, src/darker/tests/test_verification.py, src/darker/verification.py
If the AST differs after reformatting when diffing and chunking with zero context lines, search for the lowest successful number of context lines using a binary search instead of by incrementing one by one. This vastly improves performance in such problematic cases.
=> Binary search to minimize number of context lines

mypy.ini, src/darker/black_diff.py
Enable implicit re-export from Black
Black 21.x split the code base into modules. Symbols are not re-exported in the main package, so we need this Mypy directive in order to pass Mypy checks when Darker imports from Black.
We can't yet import directly from the Black submodules since we want to keep supporting Black 20.x at least for some time still.
=> Mypy & Black 21.x compatibility

CHANGES.rst, README.rst, src/darker/tests/conftest.py, src/darker/tests/test_git.py, src/darker/tests/test_main.py
Set HOME environment variable to the temporary directory the tests will
run in, avoiding any ~/.gitconfig settings that may interfere with
assumptions in the tests, particularly init.defaultBranch and
init.templateDir
Context: 
There are two settings that I'm aware of that can violate the assumption that the default branch will be called "master" when running `git init`. The older way is via the templateDir setting, which if pointed to a directory with a HEAD file containing `ref: refs/heads/main` will cause `git init` to default to `main` branch. Additionally, starting with version 2.28, git introduced a defaultBranch setting, that also allows developers to change the name of the initial branch name in a brand new repository.
This PR contains a minimal change to make the git-related …
=> Ignore ~/.gitconfig when running git tests

CHANGES.rst, mypy.ini, src/darker/help.py, src/darker/import_sorting.py, src/darker/tests/conftest.py, src/darker/tests/helpers.py, src/darker/tests/test_command_line.py, src/darker/tests/test_import_sorting.py, src/darker/tests/test_main.py
=> Fix crash when `isort` isn't installed

CHANGES.rst, src/darker/__main__.py, src/darker/git.py, src/darker/tests/test_git.py, src/darker/tests/test_main.py, src/darker/utils.py
This pull request fixes three bugs:
**AST verification** no longer erroneously fails when using `--isort`.
This bug was introduced in #94 and is present in version 1.2.3.
**Historical comparisons**, e.g. comparing two past commits like `darker --diff v1.0..v1.1` would still compare against the file on disk in the working tree, not the second commit. This has been fixed.
**Darker would write historical reformats on disk**, overwriting a newer version in the working tree. Now an exception is raised instead if a historical comparison like `darker --revision=commit1..commit2` is used without `--diff` or `--check`.
=> Fix AST verification and historical comparisons

CHANGES.rst, src/darker/__main__.py, src/darker/git.py
Instead of passing an absolute path to `git show COMMITISH:{path}` and being surprised that git isn't able to deal with absolute paths there.
This triggers when using `--revision <COMMIT_A>..<COMMIT_B>` where `COMMIT_B` is _not_ `:WORKTREE:`. That is what we want to use in our CI system to validate every single commit in a PR.
For C++ we've already been using this for years with `clang-format` for the purpose of ensuring that `git blame` always returns the commit that changed the logic of the code, not some follow up commit that reformatted it (by basically forbidding such follow up commits).
=> fix: always give git_get_content_at_revision a relative path

src/darker/tests/test_argparse_helpers.py, src/darker/tests/test_black_diff.py, src/darker/tests/test_chooser.py, src/darker/tests/test_command_line.py, src/darker/tests/test_config.py, src/darker/tests/test_diff.py, src/darker/tests/test_git.py, src/darker/tests/test_import_sorting.py, src/darker/tests/test_linting.py, src/darker/tests/test_main.py, src/darker/tests/test_main_revision.py, src/darker/tests/test_utils.py, src/darker/tests/test_verification.py
Build failure on Windows is due to #133. Rebase this after merging #142.
=> Use pytest-kwparametrize

CHANGES.rst, src/darker/__main__.py, src/darker/git.py, src/darker/import_sorting.py, src/darker/tests/test_git.py, src/darker/tests/test_main.py, src/darker/tests/test_main_revision.py
This may also fix (or might not) #67 – VS Code compatibility problem.
ping @virtuald @shangxiao @Carreau
=> Make `--diff` output identical to Black

CHANGES.rst, README.rst, src/darker/__main__.py, src/darker/command_line.py, src/darker/config.py, src/darker/help.py, src/darker/tests/test_command_line.py, src/darker/tests/test_config.py, src/darker/tests/test_main.py
=> Add the `-d` / `--stdout` option. Fixes #164.

CHANGES.rst, src/darker/git.py, src/darker/tests/test_git.py
Fixes #85.
With e.g. `darker --revision=master...`, newly created files would cause this Git error to appear on stderr:
```
fatal: Path 'newfile.py' exists on disk, but not in 'master'.
```
We already caught that situation and interpreted it properly as caused by a newly created file. In addition, the Git error messages are now silenced, but other Git errors are still logged with the `ERROR` loglevel.
Unfortunately I couldn't find a way to create a failing test, i.e. one that would be able to catch Git's stderr.
=> Hide expected Git errors from stderr

mypy.ini, src/darker/__main__.py, src/darker/black_diff.py, src/darker/tests/test_black_diff.py, src/darker/tests/test_main.py
Skip Black reformatting for files matching the `exclude`, `extend-exclude` or `force-exclude` Black configuration options. Fixes #146.
=> Respect black exclude

CHANGES.rst, setup.cfg, src/darker/__main__.py, src/darker/command_line.py, src/darker/git.py, src/darker/tests/helpers.py, src/darker/tests/test_command_line.py, src/darker/tests/test_git.py, src/darker/tests/test_main.py
~Disallow paths starting with a hyphen – those are probably due to quoting multiple arguments like `"--lint pylint"`.~
Disallow paths which don't exist as files or directories on disk (if rev2 is `WORKTREE`) or in a past revision (if rev2 points to a commit). Fixes #147 and #102.
=> Validate that paths given on command line do exist

CHANGES.rst, src/darker/tests/test_git.py
File timestamp age exceeded two seconds in [this #172 check](https://github.com/akaihola/darker/pull/172/checks?check_run_id=3218212179).
=> Increase delay tolerance in Git test

CHANGES.rst, src/darker/git.py
This was found and worked around in #163.
Git behavior reported in git-for-windows/git/issues/3344.
=> Use forward slash as the path separator for Git on Windows

CHANGES.rst, src/darker/black_diff.py
This should fix the tests and be backwards compatible
=> Fix gen_python_files usage for black>=21.7b1.dev9

setup.cfg, src/darker/black_diff.py
There were two issues with Black versions:
1. with current Black, Mypy *shouldn't* ignore extra call arguments for `black.files.gen_python_files()` (see #189), but we have to make sure a recent enough Black is used when running tests
2. Black < 21.5b1 are incompatible with at least to recently added features, so the minimum required Black version had to be bumped
=> Update black required versions

src/darker/git.py, src/darker/tests/test_git.py
This is important since we parse the output to hide expected fatal errors.
=> Always run Git in English

CHANGES.rst, src/darker/__main__.py, src/darker/tests/test_main.py
As currently written, `print_diff` assumes that that current working directory should be used as the relative path, which does not necessarily need to be the case.
Submitting the test first, for that satisfying red X to green check mark, the patch follows.
=> Fix assumption of root being CWD in print_diff

CHANGES.rst, src/darker/black_diff.py, src/darker/tests/test_black_diff.py
=> Reformat empty and all-whitespace files properly

CHANGES.rst, src/darker/__main__.py, src/darker/tests/test_main.py
With this patch, Darker _will_ modify files when called by `pre-commit -o HEAD`, and emit a warning about this being an experimental feature.
With any other values than `HEAD` for `pre-commit -o`, Darker will still refuse to modify files.
Fixes #180. See the issue for detailed discussion.
=> Allow `pre-commit -o HEAD`

CHANGES.rst, src/darker/__main__.py
Do not recompute invariant values in bisect loop.
Fixes #210.
=> Performance improvements in __main__.py

CHANGES.rst, src/darker/__main__.py, src/darker/git.py, src/darker/tests/test_git.py, src/darker/tests/test_main.py
I started off writing some code for better messages when running `darker` on a non-git repo, to fix #71, but then ended up writing enough to make it work anyway.
With this PR, you can `mkdir /tmp/test ; cd /tmp/test ; darker .` and no compaints are raised. Same goes for
```diff
$ mkdir -p /tmp/test ; cd /tmp/test ; echo "print   ('hello'  )" > a.py; darker --diff .;
--- a.py
+++ a.py
@@ -1 +1 @@
-print   ('hello'  )
+print("hello")
```
Opening this up for discussion to see if this if @akaihola would be amenable to something like this, before I start adding tests. In particular,  this will conflict with #138, though I also ran into AST verification failing when using `--isort`, my fix is slightly different (perhaps wrong?). 
#139 also came out of the work on this, but I decided to submit …
=> Allow running on plain (non-git) directories

src/darker/__main__.py, src/darker/git.py, src/darker/tests/conftest.py, src/darker/tests/test_git.py
- prevent passing through `GIT_*` environment variables in tests
- better logging
- working directory fixes
=> Improve Git robustness

CHANGES.rst, src/darker/git.py, src/darker/tests/conftest.py, src/darker/tests/test_git.py
On NixOS systems Git is in a funky non-standard directory which isn't included in the system default `$PATH`. So we need to pass through `$PATH` when invoking Git subprocesses.
Fixes #245.
=> Keep `$PATH` intact so Git is found on NixOS

.github/workflows/python-package.yml, CHANGES.rst, constraints-oldest.txt, mypy.ini, setup.cfg, src/darker/black_compat.py, src/darker/config.py, src/darker/import_sorting.py, src/darker/tests/conftest.py, src/darker/tests/test_black_diff.py, src/darker/tests/test_import_sorting.py, src/darker/tests/test_main.py
=> Add compatibility with Black >= 22.1

CHANGES.rst, src/darker/__main__.py, src/darker/tests/test_main.py
=> No additional newline with `--stdout` flag.

CHANGES.rst, src/darker/__main__.py, src/darker/git.py, src/darker/tests/test_git.py, src/darker/tests/test_main.py
=> VSCode `.py.tmp` file should be reformatted

CHANGES.rst, README.rst, action.yml
=> Update the GitHub Action to use Darker 1.4.0

.github/workflows/python-package.yml
I accidentally left these disabled in #248.
=> Re-enable Win and Python 3.6/3.7/3.8/3.9 builds

CHANGES.rst, README.rst
=> Document VSCode / `--lint` incompatibility

.github/workflows/python-package.yml, CHANGES.rst
This happened first in the [ubuntu-latest](https://github.com/akaihola/darker/runs/5274554724?check_suite_focus=true) and [macos-latest](https://github.com/akaihola/darker/runs/5274554796?check_suite_focus=true) NixOS builds for #300. And it wasn't a transient problem, since they failed again (see build \#860 for [ubuntu-latest](https://github.com/akaihola/darker/runs/5277753959?check_suite_focus=true) and [macos-latest](https://github.com/akaihola/darker/runs/5277754008?check_suite_focus=true).
But for this PR, strangely, the [ubuntu-latest nixos build](https://github.com/akaihola/darker/runs/5277677163?check_suite_focus=true) succeeds. It's hard for me to believe that the code changes in #300 would have caused the failure.
I'll still use this PR to find a fix..
=> NixOS build failed when `pytest-darker` called `pylint`

.github/workflows/python-package.yml, .github/workflows/test-future.yml, CHANGES.rst, constraints-future.txt
Fixes #262.
Also adds use of `--upgrade --upgrade-strategy=eager` for pip when installing packages with `constraints-future.txt`. This way not only Black and `isort` are from their `main` branches, but also we get newest releases for all other dependencies as well.
=> Include `isort@main` in `test-future` workflow

CHANGES.rst, src/darker/tests/test_git.py
4.5 seconds passed in [a unit test on Windows](https://github.com/akaihola/darker/runs/5306288849?check_suite_focus=true#step:5:105) while only 3 seconds was allowed when checking whether the file modification time falls in the correct ballpark.
=> Fix slow windows test

constraints-oldest.txt, release_tools/update_contributors.py, setup.cfg
`# type: ignore[attr-defined]` must be removed from `click.echo(yaml.dump(users))` when upgrading.
=> Upgrade to `mypy==0.940`

.github/workflows/python-package.yml, .github/workflows/test-bump-version.yml, CHANGES.rst, pyproject.toml, release_tools/bump_version.py
The `release_tools/bump_version.py` script bumps version numbers and milestone links in several files. There's also the `.github/workflows/test-bump-version.yml` workflow which verifies that the regular expressions are in sync with the files to modify.
=> Version bump tool

CHANGES.rst, README.rst, mypy.ini, src/darker/__main__.py, src/darker/command_line.py, src/darker/concurrency.py, src/darker/config.py, src/darker/help.py, src/darker/tests/test_command_line.py, src/darker/tests/test_concurrency.py, src/darker/tests/test_main.py, src/darker/tests/test_main_blacken_single_file.py, src/darker/tests/test_main_revision.py
=> --jobs argument

CHANGES.rst, src/darker/git.py
This was an interesting find reported by the [flake8-bugbear](https://pypi.org/project/flake8-bugbear/) plugin:
>```
>B019 Use of `functools.lru_cache` or `functools.cache` on class methods can lead to memory leaks.
>      The cache may retain instance references, preventing garbage collection.
>```
See [Python functools lru_cache with instance methods: release object](https://stackoverflow.com/questions/33672412/python-functools-lru-cache-with-instance-methods-release-object) on StackOverflow for more information.
=> Avoid memory leak from using `@lru_cache` on a method

.github/workflows/bandit.yml
In the [akaihola/bandit-report-artifacts@use-config](https://github.com/akaihola/bandit-report-artifacts/commits/use-config) branch (see ioggstream/bandit-report-artifacts#8), the second `bandit` call from inside `main.py` now uses the configuration file as well. Annotations should now match the check status when looking at GitHub Workflow results.
=> Fix bandit reporting in GitHub Workflows by using my own branch of the action

.github/workflows/bandit.yml, .github/workflows/python-package.yml, .github/workflows/test-bump-version.yml, .github/workflows/test-future.yml
https://github.com/actions/checkout/releases
=> Upgrade GitHub Action checkout

CHANGES.rst, CONTRIBUTORS.rst, README.rst, contributors.yaml, src/darker/git.py, src/darker/tests/conftest.py, src/darker/tests/test_git.py, src/darker/tests/test_utils.py, src/darker/utils.py
Black can format files encoded with an encoding other than UTF-8, based on the encoding cookie present in the first two lines. Darker is also supposed to format those files, but an exception is raised instead.
The exception happens because all the output from git is decoded with UTF-8, including calls to `git show <revision>:<path>` that returns the binary content of a file from the history. If a file used an encoding other than UTF-8, the decoding fails.
I introduce `TextDocument.from_bytes()` to create a `TextDocument` from the raw binary content of a file, automatically detecting the encoding used, and use this new factory when loading a file from disk or from a revision in the git history.
=> Handle files not encoded with UTF-8

CHANGES.rst, README.rst, action.yml, action/main.py, action/tests/test_main.py
Fixes #337. Being tested in akaihola/pgtricks#18.
Linter support was added in #313.
=> Allow constraining linter versions in GitHub Action configuration

README.rst
Add information on how to use emacs with darker using 
https://github.com/purcell/emacs-reformatter/ library
=> Add information about using Emacs with darker

README.rst
Added link to original article and quoted the original text from the article
Fixes #294
=> Updated README for issue#294

CHANGES.rst, src/darker/diff.py, src/darker/git.py, src/darker/multiline_strings.py, src/darker/tests/test_diff.py, src/darker/tests/test_git.py, src/darker/tests/test_main_blacken_single_file.py, src/darker/tests/test_multiline_strings.py
Treating large docstrings as separate chunks can cause to weird behavior, e.g. "reformat loops" in which some lines are repeatedly indented and unindented by Darker.
Fixes #240.
```python
from pathlib import Path
from tokenize import tokenize, STRING
from darker.utils import TextDocument
src = TextDocument.from_file(Path("setup.py"))
readline = (f"{line}\n".encode(src.encoding) for line in src.lines).__next__
multiline_string_linespans = [
(t.start[0], t.end[0]) for t in tokenize(readline)
if t.type == STRING and t.end[0] > t.start[0]
]
```
=> Format docstrings as complete chunks

CHANGES.rst, action/main.py
`os.getenv` default is only used if key is not defined, not if the value resolves to False.
=> (action) fix getting revision and commit_range

CHANGES.rst, README.rst, src/darker/__main__.py, src/darker/command_line.py, src/darker/concurrency.py, src/darker/config.py, src/darker/help.py, src/darker/tests/test_command_line.py
Fixes #335.
The `--jobs` option was originally proposed in #178 and implemented in #179.
=> Rename `--jobs` to `-W` / `--workers`

CHANGES.rst, src/darker/__main__.py, src/darker/diff.py, src/darker/git.py, src/darker/import_sorting.py, src/darker/tests/test_git.py, src/darker/tests/test_import_sorting.py, src/darker/tests/test_main.py, src/darker/tests/test_main_blacken_single_file.py
Fixes #72:
>The problem with applying isort modifications "surgically" is in the fact that isort may (and often does) change the order of lines.
>
>Could we consider all changes by isort as one contiguous diff chunk, and apply it if any line in `edited_linenums` falls inside that chunk? Is there an edge case where isort only modifies part of the import lines, and a user edit happens to an import outside that part? I can't see a problem there. The important thing is that either all or none of the isort modifications are applied.
The changes are pretty involved. Here's a summary for reviewers:
- some variable renames for clarity:
- `path_in_repo` -> `relative_path_in_rev2`
- `src` -> `absolute_path_in_rev2`
- `relative_path` -> `relative_path_in_rev2`
- `_isort_and_blacken_single_file()` …
=> isort only if imports at the top of the module were edited

.github/workflows/python-package.yml, CHANGES.rst, default.nix
Fixes macOS build error (see e.g. [`text-nixos (macos-latest)` in build #1248](https://github.com/akaihola/darker/runs/5994916141)).
=> Update `cachix/install-nix-action` to `v17`, downgrade to Python 3.9 on macOS Nix

CHANGES.rst, constraints-oldest.txt, setup.cfg, src/darker/config.py, src/darker/tests/test_highlighting.py
Setting `NO_COLOR` to any non-empty value will disable syntax highlighting even on terminal output. This overrides the `color = true` setting in `pyproject.toml`, but will be overridden by `PY_COLORS=1` or the `--color` command line option, if those are present.
Fixes #355.
Previously, #353 added a command line options, a `pyproject.toml` option and the `PY_COLORS` environment variable to for enabling/disabling syntax highlighting.
See [earlier discussion](https://github.com/akaihola/darker/pull/353#discussion_r846746769) in #353, and pypa/pip#10909, for the reasoning behind supporting both `NO_COLOR` and `PY_COLORS`.
=> Support the `NO_COLOR` environment variable

CHANGES.rst, src/darker/command_line.py, src/darker/config.py, src/darker/tests/test_command_line.py, src/darker/tests/test_config.py
Darker's own configuration is now read from the `PATH` TOML file when `-c PATH` or `--config PATH` is used.
Fixes #244 (partially).
=> Use `-c PATH`/`--config PATH` for Darker config

CHANGES.rst, src/darker/git.py, src/darker/tests/test_main.py
The fix is to always consider the repository root to exist in all historical commits.
Fixes #362.
=> Fix `darker -r a..b .`

CHANGES.rst, src/darker/linting.py
**Ignore .pylintrc lines in Pylint output:** Pylint may notify about obsolete options in `.pylintrc`. Since that file is probably outside the common root directory of `.py` files listed on the Darker command line, it needs to be ignored to avoid errors.
**Fix a typo in `CHANGES.rst`:** this caused a test failure from `codespell`
=> Fix various non-test build failures

CHANGES.rst, src/darker/__main__.py, src/darker/tests/test_main_blacken_single_file.py
This refactoring simplification is in preparation for unified exclusions (#377), which is in preparation for `flynt` support (#266 & #308).
Merge this before any of those.
=> Refactoring: Care only if import sorting was done, not whether isort was run or not.

.github/workflows/help-in-readme.yml
Show the output from `darker --options-for-readme` so it can be manually compared to the README to find out the mismatch.
=> Better error reporting from `help-in-readme.yml`

CHANGES.rst, src/darker/linting.py, src/darker/tests/conftest.py, src/darker/tests/test_linting.py
Fixes #374.
- either always show such messages, or never show them (design decision needed)
- either always show such messages, or never show them (design decision needed)
=> Fix linter output parsing on Windows

CHANGES.rst, src/darker/black_diff.py
=> Compatibility with black-22.10.1.dev19+gffaaf48

.github/workflows/safety.yml
This way Safety actually checks the dependencies of Darker, not everything that happens to be installed in the CI image.
=> `pip-compile` to get dependencies for safety check

.github/workflows/help-in-readme.yml, CHANGES.rst
This hopefully fixes the recently introduced build problem, see e.g. [build #205](/akaihola/darker/actions/runs/3732587943/jobs/6332350304).
=> No development install in `help-in-readme.yml`

.github/workflows/test-bump-version.yml, CHANGES.rst, release_tools/bump_version.py
This helps with
```python
File "/home/runner/work/darker/darker/release_tools/bump_version.py", line 269, in get_milestone_numbers
raise TypeError(f"Expected a JSON list from GitHub API, got {milestones}")
TypeError: Expected a JSON list from GitHub API, got {'message': "API rate limit exceeded for 13.64.11.212. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", 'documentation_url': 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'}
Error: Process completed with exit code 1.
```
seen e.g. in [build #526](/akaihola/darker/actions/runs/3732869497/jobs/6332892263).
=> Use `GITHUB_TOKEN` in the `test-bump-version` workflow

README.rst
Apparently my PR #414 had a minor RST spacing/indentation issue.
This should fix it
=> Fixup RST spacing issue from PR #414

.github/workflows/python-package.yml, CHANGES.rst
Ensures consistent formatting of the Darker code base itself.
=> Pin Black to 22.12.0 in CI build

.github/workflows/python-package.yml, .github/workflows/test-future.yml, CHANGES.rst, default.nix, setup.cfg
Python 3.11 was [released on 2022-10-24](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk) 🚀 
[![image](https://user-images.githubusercontent.com/1324225/198233993-5b79523b-370f-4316-a4be-9403c8209068.png)](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk)
Also test Python 3.12-dev.
=> Add support for Python 3.11

CHANGES.rst, src/darker/git.py, src/darker/tests/conftest.py
=> Omit `--initial-branch=master` on old Git versions

.github/workflows/test-future.yml, README.rst, action.yml, action/main.py, release_tools/bump_version.py
Fixes #382.
Also related to
- #403 
- #429
- #426 
- #425 
- #412
- #404 
- #394
- #284
- #270
- #269
- #268 
- #267
- #264
- #262 
- #189 
- #186 
- #183
- #135
=> Guard against Black compatibliity breakage

CHANGES.rst, README.rst
It obtains the commit range automatically.
Fixes #410.
=> Remove revision from GitHub Action example

.github/workflows/test-future.yml, setup.cfg
Fixes CVE-2020-26137 found by Safety:
```
-> Vulnerability found in urllib3 version 1.25.8
Vulnerability ID: 38834
Affected spec: <1.25.9
ADVISORY: Urllib3 before 1.25.9 allows CRLF injection if the attacker
controls the HTTP request method, as demonstrated by inserting CR and LF...
CVE-2020-26137
For more information, please visit
https://pyup.io/vulnerabilities/CVE-2020-26137/38834/
```
=> Update vulnerable dependencies (Nov 2022)

CHANGES.rst, README.rst, release_tools/bump_version.py
=> Document how to pin reformatters/linters in pre-commit configuration

CHANGES.rst, src/darker/git.py
In `_git_check_output()`, stderr output needs to be adapted to work both with `encoding=None` and `encoding="utf-8"`.
Required for #393.
=> Fix Git error output

.github/workflows/python-package.yml, CHANGES.rst, README.rst, pyproject.toml, src/darker/__main__.py, src/darker/black_diff.py, src/darker/command_line.py, src/darker/config.py, src/darker/help.py, src/darker/tests/test_black_diff.py, src/darker/tests/test_command_line.py
Adds support for target-version in pyproject.toml
I'm not sure how to add (or even run) tests, so help on that would be appreciated.
Also, I've ran black and it formats quite a few code chunks. I'm I running it right?
=> support target-version

.github/workflows/python-package.yml, CHANGES.rst, README.rst, src/darker/git.py, src/darker/linting.py, src/darker/tests/test_linting.py
This deals with quoting correctly.
=> Split/join command lines using `shlex` from Python stdlib

CHANGES.rst, README.rst, src/darker/__main__.py, src/darker/black_diff.py, src/darker/diff.py, src/darker/git.py, src/darker/linting.py, src/darker/tests/conftest.py, src/darker/tests/test_black_diff.py, src/darker/tests/test_diff.py, src/darker/tests/test_git.py, src/darker/tests/test_linting.py, src/darker/tests/test_main.py
Hide linter messages which were already present in the baseline. Track unmodified blocks of code which are moved up or down due to other changes, and match linter messages even though the line number might have changed since the baseline.
Fixes #383 and #380.
=> Run linters twice: 1) baseline, 2) current; then show new messages

CHANGES.rst, setup.cfg, src/darker/diff.py
=> Add docstring linting to the Darker repo

.coveragerc, CHANGES.rst
This enables the use of `cov_to_lint.py` together with Darker.
=> Configure `coverage` to use relative paths in the Darker repo

.github/workflows/help-in-readme.yml, .github/workflows/mypy.yml, CHANGES.rst, README.rst, constraints-oldest.txt, mypy.ini, setup.cfg, src/darker/__main__.py, src/darker/command_line.py, src/darker/config.py, src/darker/diff.py, src/darker/fstring.py, src/darker/git.py, src/darker/help.py, src/darker/import_sorting.py, src/darker/linting.py, src/darker/tests/helpers.py, src/darker/tests/test_command_line.py, src/darker/tests/test_fstring.py, src/darker/tests/test_main.py, src/darker/tests/test_main_blacken_and_flynt_single_file.py
=> Add conversion to f-strings using `flynt`

CHANGES.rst, action/tests/test_main.py, src/darker/black_diff.py, src/darker/tests/test_argparse_helpers.py, src/darker/tests/test_black_diff.py, src/darker/tests/test_chooser.py, src/darker/tests/test_command_line.py, src/darker/tests/test_concurrency.py, src/darker/tests/test_config.py, src/darker/tests/test_diff.py, src/darker/tests/test_git.py, src/darker/tests/test_import_sorting.py, src/darker/tests/test_linting.py, src/darker/tests/test_main.py, src/darker/tests/test_main_revision.py, src/darker/tests/test_multiline_strings.py, src/darker/tests/test_utils.py, src/darker/tests/test_verification.py
A Pylint update must have caused this to suddenly appear.
=> Satisfy Pylint's `use-dict-literal` check

CHANGES.rst, README.rst, src/darker/__main__.py, src/darker/command_line.py, src/darker/config.py, src/darker/git.py, src/darker/help.py, src/darker/linting.py, src/darker/tests/test_config.py, src/darker/tests/test_git.py, src/darker/tests/test_linting.py, src/darker/tests/test_main.py, src/darker/tests/test_main_blacken_and_flynt_single_file.py, src/darker/tests/test_main_stdin_filename.py
=> `stdin` mode

.github/workflows/darker-flake8.yml, src/darker/git.py, src/darker/linting.py, src/darker/tests/test_git.py
Fixes #467.
`actions/checkout@v3` clones a repository in a way which doesn't allow checking out arbitrary branches after making a local clone using `git clone <path1> <path2>`. This effectively broke linting in the Darker action in version 1.7.0.
The fix is to use `git worktree` instead of `git clone` and `git checkout` to create a local copy of the repository.
This PR also adds a CI workflow which tests the Darker action. A Flake8 lint is run in that workflow.
=> Use `git workflow` for generating the linter baseline

action/main.py
```python
>> Issue: [B603:subprocess_without_shell_equals_true] subprocess call - check for execution of untrusted input.
Severity: Low   Confidence: High
CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
More Info: https://bandit.readthedocs.io/en/1.7.5/plugins/b603_subprocess_without_shell_equals_true.html
Location: ./action/main.py:21:0
20	
21	run([sys.executable, "-m", "venv", str(ENV_PATH)], check=True)
22	
```
=> Ignore Bandit reports in action `run()`

src/darker/tests/test_highlighting.py
From Mypy:
```
Unused "type: ignore" comment, use narrower `[method-assign]` instead of `[assignment]`
```
=> Do `ignore[method-assign]` as suggested by Mypy

CHANGES.rst, setup.cfg
This works around the internal API change. In the next minor release compatibility with Flynt 0.78 will be introduced.
=> Temporarily limit Flynt to versions before 0.78

action.yml
This should avoid the problem of looking for the `commit-range` in the yet unreleased version when running the CI build in a release branch e.g. [in this build](/akaihola/darker/actions/runs/4523963269/jobs/7967467444?pr=482):
```
Error: Unable to resolve action `akaihola/darker@1.7.1`, unable to find version `1.7.1`
```
=> Run `commit-range` action from local checkout

CHANGES.rst, action.yml
=> Fix local action outside of this repo

CHANGES.rst, src/darker/git.py, src/darker/multiline_strings.py, src/darker/tests/test_multiline_strings.py
Partially fixes #495.
Starting from Python 3.12, `tokenizer` emits an f-string and a triple-quoted f-string as a sequence of tokens starting with `FSTRING_START` and ending with `FSTRING_END`, instead of a single `STRING` token.
Note that as expected, we're still getting the [25 other test failures](/akaihola/darker/actions/runs/5118177370/jobs/9201949165?pr=496) which will be fixed by #497:
```python
FAILED action/tests/test_main.py::test_creates_virtualenv - ModuleNotFoundError: No module named 'pkg_resources'
FAILED action/tests/test_main.py::test_installs_packages[run_main_env0-expect0] - ModuleNotFoundError: No module named 'pkg_resources'
FAILED action/tests/test_main.py::test_installs_packages[run_main_env1-expect1] - ModuleNotFoundError: No module named 'pkg_resources'
FAILED …
```
=> Fix Python 3.12 compatibility in multi-line string scanning

CHANGES.rst, constraints-oldest.txt, setup.cfg, src/darker/linting.py, src/darker/tests/test_linting.py
=> Avoid Mypy error when there's an `__init__.py` in the repo root

.github/workflows/pylint.yml, CHANGES.rst, action.yml, action/main.py, setup.cfg
Partially fixes #495.
`pkg_resources` is no longer available by default in the environment since `setuptools` was dropped in Python 3.12. Instead of installing one of those, we're now using [pip-requirements-parser](https://pypi.org/project/pip-requirements-parser/) as a more stable solution since `pkg_resources` is [deprecated](https://setuptools.pypa.io/en/latest/pkg_resources.html) in favor of `importlib` which doesn't provide tooling for parsing requirements.
=> Fix Python 3.12 compatibility of the GitHub Action

CHANGES.rst, src/darker/config.py, src/darker/tests/test_main_stdin_filename.py
Fixes #492. Makes Darker behave like Black.
Required:
=> Allow `-` as `SRC` when using `--stdin-filename`

.github/workflows/python-package.yml, CHANGES.rst, default.nix
This way we get early notification of incompatibilities.
=> Run NixOS tests on NixOS unstable and Python 3.11

setup.cfg, src/darker/fstring.py, src/darker/tests/helpers.py
Updates the existing flynt-0.78-compatibility branch (https://github.com/akaihola/darker/pull/480) to support, additionally, flynt-1.0.0. It also fixes various issues with the existing flynt 0.78 compatibility changes (e.g. gracefully handling non-installed flynt).
All tests pass locally on Python 3.11, with flynt versions 0.77, 0.78, and 1.0.0, and without flynt installed.
Code formatted with black and isort.
=> Fix compatibility with Flynt v1.0.0

CHANGES.rst, src/darker/config.py, src/darker/tests/test_config.py
Fixes #502.
Also normalizes the `pyproject.toml` dump seen in debug log level to always use hyphens instead of underscores in option keys.
=> Allow hyphens for option keys in `pyproject.toml`

.github/workflows/python-package.yml, default.nix, pytest.ini, src/darker/concurrency.py, src/darker/tests/helpers.py
- Ignore import mismatch when running Pytest
- Add a Pylint disable (error appeared with a recent Pylint version)
- Ignore Flake8 BaseException lint message (appeared with a recent Flake8 update)
=> Fix miscellaneous test failures

.github/workflows/python-package.yml
Somehow this sidesteps the problem of plugins from `conftest.py` not being available.
=> Run Pytest in installed package in Nix test

.github/workflows/python-package.yml, CHANGES.rst
Note: Dropping support for Python 3.7 will come in a separate PR.
=> Drop Python 3.7 tests

CHANGES.rst, README.rst
The current version makes the call fail as the --lint argument is interpreted as a file.
Each item of the argument list must be on its own line.
=> Fix args list for pre-commit hook

README.rst
Change: `--lint="pylint --ignore='setup.py'""` to `--lint="pylint --ignore='setup.py'"` to be correct
=> Fix typo in pylint example, unmatched " Update README.rst

setup.cfg, src/darker/black_diff.py, src/darker/tests/test_black_diff.py
Black didn't use the `.gitignore` file, because `gen_python_files()` will be called with `gitignore_dict=None` and `None` will disable the `.gitignore` usage.
see: https://github.com/akaihola/darker/discussions/323#discussioncomment-6676869
=> Bugfix black .gitignore usage

.github/ISSUE_TEMPLATE/bug_report.md, CHANGES.rst, README.rst, action.yml, src/darker/version.py
Primary reason for the release is to prevent upgrading Black to 24.2 and beyond in the 1.7.x series of Darker. The compatibility issue will be fixed in 1.8.0, and newer Black versions allowed again.
=> Release 1.7.3

setup.cfg, src/darker/__main__.py, src/darker/fstring.py, src/darker/tests/helpers.py
Fixes #472 and #541.
We temporarily limited Flynt to version 0.77 and earlier in version 1.7.1 (see #474). This patch fixes compatibility with Flynt 0.78 and 1.0.x.
=> Fix compatibility with Flynt 0.78 and 1.0.0

.github/workflows/bandit.yml, CHANGES.rst
=> Update to bandit-report-artifacts@v1.7.4 in CI

.github/workflows/test-bump-version.yml, .yamllint, CHANGES.rst, release_tools/bump-version-patterns.yaml, setup.cfg
The new repository will contain common development, testing and releasing tooling for Darker, Graylint and Darkgraylib.
=> Move `bump_version.py` to `darkgray-dev-tools`

.github/workflows/python-package.yml, CHANGES.rst, constraints-future.txt
=> Test against Flynt `master` branch in the CI build

CHANGES.rst, README.rst, release_tools/bump-version-patterns.yaml
This just sets the correct git tag (`v2.0.0` instead of `2.0.0`).
Thanks for your work!
=> Update pre-commit hook in README.rst

.github/workflows/python-package.yml, CHANGES.rst
Some C extension builds fail with Python 3.13-dev on Windows and macOS.
We should remove exclusions after Python 3.13 release.
Copied from https://github.com/akaihola/darkgraylib/pull/49.
=>  Skip tests on Python 3.13-dev in Windows and macOS

CHANGES.rst, setup.cfg
This fixes README `--help` formatting when re-generating it.
=> Update to Darkgraylib 1.1.1

CHANGES.rst, README.rst
This avoids ReStructuredText rendering issues.
=> Escape pipe symbols (`|`) in the README

CHANGES.rst, README.rst, src/darker/config.py
Fixes #523
This makes [VSCode black-formatter extension](https://github.com/microsoft/vscode-black-formatter/tree/main) configuration easier on VSCode.
=> Allow `--stdout <...> -`

CHANGES.rst, README.rst, constraints-oldest.txt, pyproject.toml, setup.cfg, src/darker/command_line.py, src/darker/config.py, src/darker/help.py, src/darker/tests/test_command_line.py
Fixes #447
Steps before this PR can be merged:
=> Deprecate `skip_*` Black options in `[tool.darker]`

mypy.ini, src/darker/tests/test_import_sorting.py
This fixes test failures when running tests from a cwd which isn't in a Git repository.
Fixes #510
=> Run import sorting tests in a temporary Git repo

setup.cfg
This allows Mypy to understand typing when doing an editable install. See:
https://github.com/python/mypy/issues/13392#issuecomment-2026018615
=> Include `.pyi` files in package data

CHANGES.rst, src/darker/__main__.py, src/darker/git.py, src/darker/tests/test_git.py
=> Fix handling of relative paths and running from non-Git-root

README.rst
Darker follows Black's choices for `--target-version`, and `py313` came in from there. So let's update our README accordingly.
This needs to be fixed before #595 which is in turn needed for #591.
=> Add `py313` to `--target-version` choices

CHANGES.rst, setup.cfg
Airium 0.2.3 to 0.2.5 wheel metadata isn't supported by Pip >= 24.1. Airium 0.2.6 fixes the metadata. `darkgray-dev-tools==0.1.1 updates Airium to version 0.2.6.
This needs to be fixed before #595 which is in turn needed for #591.
=> Fix CI compatibility with Pip >= 24.1

CHANGES.rst, src/darker/command_line.py
the argparser in the darkgraylib was using the library version instead of the version of the module calling it
See akaihola/darkgraylib#64
=> A fix for darkgraylib requiring version for argparser

CHANGES.rst, constraints-oldest.txt, setup.cfg, src/darker/__main__.py, src/darker/tests/test_command_line.py, src/darker/tests/test_main_stdin_filename.py
Fixes #592 
- 2 for file not found
- 3 for invalid arguments
- 4 for missing dependencies
- 123 for unknown failures
=> Refine exit codes

CHANGES.rst, src/darker/git.py, src/darker/tests/test_git.py, src/darker/tests/test_main_revision.py
~Adds an option `--modified-only/-m` to ignore renamed files from being checked.~
Make the filter the default behaviour. Possibly add an option to include renamed files or not, depending on discussions below
Fixes #544
=> Filter out unmodified files from list of changed files

src/darker/tests/test_git.py
Change in Darkgraylib for Git environment broke Darker tests. The environment is already tested in Darkgraylib, ignore it in Darker tests.
=> Ignore environment in Git tests

CHANGES.rst, constraints-oldest.txt, setup.cfg
=> Update to Darkgraylib 2.0.1 (fixes Git "dubious ownership" error)

.github/workflows/flake8.yml
Needed while waiting for PyCQA/flake8-bugbear#490 to land in a release.
=> fix: avoid flake8-bugbear version with broken deps

CHANGES.rst, src/darker/__main__.py
In some PRs, tests started failing on Python 3.8 and 3.9 when run in Windows. This was due to a Python bug, see python/cpython#82852. This PR adds a special case for those environments until we drop support for Python 3.9.
=> Work around `Path.resolve` bug in Windows py38/py39

.github/workflows/pylint.yml, CHANGES.rst, setup.cfg
This way we continue to support Python 3.8 for just a bit longer. Pylint 3.3.0 already dropped support for Python 3.8.
=> fix: keep Pylint at max version 3.2.7

CHANGES.rst, README.rst, constraints-oldest.txt, pyproject.toml, setup.cfg, src/darker/__main__.py, src/darker/command_line.py, src/darker/config.py, src/darker/tests/test_command_line.py, src/darker/tests/test_config.py
These options were deprecated in Darker 2.1.1 (see #578). They can still be used as command line arguments or in the `[tool.black]` section of the configuration file.
See also:
- #50 
- #152 
- #502
:orange_circle: Pending review is [delaying](https://github.com/users/akaihola/projects/4/views/2?pane=info&statusUpdateId=50063) Darker 3.0.0 release.
=> Remove deprecated options in `[tool.darker]`

CHANGES.rst, README.rst, src/darker/command_line.py, src/darker/config.py, src/darker/tests/test_command_line.py
The only supported value for now is `black`.
This is the first step to add supports for multiple formatter backends (see [many-formatters](https://github.com/users/akaihola/projects/4/views/5) sub-project).
Fixes #562
Depends on:
Enables:
- #738
=> Add `formatter` command line and config option

.github/workflows/flake8.yml, .github/workflows/help-in-readme.yml, .github/workflows/isort.yml, .github/workflows/mypy.yml, .github/workflows/pylint.yml, .github/workflows/python-package.yml, .github/workflows/pyupgrade.yml, .github/workflows/safety.yml, .github/workflows/test-bump-version.yml, src/darker/black_diff.py
Solve the problem introduced by GitHub switching `ubuntu-latest` to Ubuntu 24.04. See e.g. [build #2497](/akaihola/darker/actions/runs/11308368324/job/31451129452?pr=738).
Also speeds up builds.
Probably we should pin to `ubuntu-24.04` and update in a controlled manner to prevent similar issues in the future.
=> Use uv and/or non system Python in CI workflows

.github/workflows/dependabot.yml, CHANGES.rst
=> Add dependabot for dependency upgrades

CHANGES.rst, src/darker/config.py, src/darker/tests/test_command_line.py
Included `flynt` in DarkerConfig options.
Also sorted config options alphabetically. 
Fixes #745.
=> fix: include flynt in darkerconfig

constraints-oldest.txt, pyproject.toml, setup.cfg, src/darker/tests/conftest.py, src/darker/tests/helpers.py, src/darker/tests/test_command_line.py, src/darker/tests/test_git.py, src/darker/tests/test_import_sorting.py, src/darker/tests/test_main.py, src/darker/tests/test_main_format_edited_parts.py, src/darker/tests/test_main_isort.py, src/darker/tests/test_main_reformat_and_flynt_single_file.py, src/darker/tests/test_main_revision.py, src/darker/tests/test_main_stdin_filename.py
This is done by using the new module-scoped Git repository fixture from Darkgraylib.
To get aggregate timings for parameterized tests:
```bash
pip install pytest-reportlog
pytest --report-log=pytest.log.json
python analyze_pytest_log.py
```
<details>
<summary>analyze_pytest_log.py</summary>
```python
import json
from collections import defaultdict
def aggregate_test_durations(log_contents):
"""Aggregate durations of parameterized tests from pytest-reportlog output.
Args:
log_contents (str): The contents of the pytest-reportlog file
Returns:
dict: A dictionary mapping test names to their total duration
"""
test_durations = defaultdict(float)
for line in log_contents.strip().split("\n"):
try:
report = json.loads(line)
full_nodeid = report["nodeid"]
base_name = full_nodeid.split("[")[0] …
```
=> Speed up parameterized tests which use Git

CHANGES.rst, README.rst, action/main.py, action/tests/test_main.py, setup.cfg, src/darker/command_line.py, src/darker/configuration/__init__.py, src/darker/configuration/target_version.py, src/darker/files.py, src/darker/formatters/black_formatter.py, src/darker/help.py, src/darker/tests/helpers.py, src/darker/tests/test_command_line.py, src/darker/tests/test_files.py, src/darker/tests/test_formatters_black.py, src/darker/tests/test_main.py, src/darker/tests/test_verification.py, src/darker/verification.py
This allows installing Darker without needing to install Black, and running e.g.
```bash
darker --formatter=none --isort
darker --formatter=none --flynt
```
and, once #744 has been merged, this will also work without needing to install Black:
```bash
darker --formatter=ruff
```
Before reviewing or merging this one:
=> Drop black dependency

src/darker/formatters/black_formatter.py, src/darker/formatters/black_wrapper.py, src/darker/tests/helpers.py, src/darker/tests/test_command_line.py, src/darker/tests/test_formatters_black.py, src/darker/tests/test_main.py
Thanks @jedie!
From [a review comment to #744]:
>Maybe move all import from black into a own package and handle import error there? So it's guaranteed that the own error message from above will always appear?
So `black_wrapper.py` now first tries to `import black` and gives a nice error message if it doesn't succeed. Upon success, it then proceeds to importing needed internals from within Black.
[a review comment to #744]: /akaihola/darker/pull/744#discussion_r1862595926
=> Separate module for Black imports

README.rst, pyproject.toml, setup.cfg, src/darker/__main__.py, src/darker/formatters/base_formatter.py, src/darker/formatters/black_formatter.py, src/darker/formatters/formatter_config.py, src/darker/formatters/none_formatter.py, src/darker/formatters/ruff_formatter.py, src/darker/tests/test_command_line.py, src/darker/tests/test_command_line_ruff.py, src/darker/tests/test_formatters_black.py, src/darker/tests/test_formatters_black_compatible.py, src/darker/tests/test_formatters_ruff.py, src/darker/tests/test_main.py, src/darker/tests/test_main_format_edited_parts.py, src/darker/tests/test_main_reformat_and_flynt_single_file.py, src/darker/tests/test_main_stdin_filename.py
=> Add support for Ruff as a code-formatter

.github/dependabot.yml, CHANGES.rst
Fixes #788
Enforcing newest versions of Darker's dependencies may cause a problem for those users who like to install Darker in the same environment as the package they are reformatting. Their package may have an upper version limit for a dependency, e.g. to prevent an unintended update to an incompatible major version. If Darker then requires a minimum version newer than that limit, the installation of Darker will fail.
It's reasonable to keep Dependabot security updates (based on the [Github Advisory Database](https://github.com/advisories)) enabled, but for the above reasons, Dependabot version updates should in my opinion be disabled. We should support oldest possible non-vulnerable versions of our dependencies, and yet in a fresh environment users will still get the newest versions …
=> Disable dependabot version updates

src/darker/files.py
Thanks @clintonsteiner for the [performance] and [documentation] suggestions in your review for #744!
[performance]: /akaihola/darker/pull/744#discussion_r1792406439
[documentation]: /akaihola/darker/pull/744#discussion_r1792407523
=> Improve `filter_python_files()`

CHANGES.rst, constraints-oldest.txt, setup.cfg, src/darker/tests/test_main_drop_changes_on_unedited_lines.py
=> Fix handling of files with exotic newlines

.github/workflows/test-working-directory.yml, CHANGES.rst, action.yml, action/main.py, action/tests/test_main.py
:orange_circle: Pending review is [delaying](https://github.com/users/akaihola/projects/4/views/2?pane=info&statusUpdateId=50063) Darker 3.0.0 release.
---
This patch introduces the following changes to the Darker GitHub Action:
- new `working-directory` input option (defined in `action.yml`)
- new `exitcode` and `stdout` outputs, and Python helpers for setting them
- use the `commit-range` action straight from the current Darker Git checkout
- install `pip-requirements-parser` in a separate action step instead of the entrypoint script
- cache the Python environment
- exit with code 21 if specified `working-directory` doesn't exist
- refactor `pip install` into a helper function
- only create virtualenv if it doesn't already exist
- correct GitHub URL when `version` starts with `@` …
=> GH action to respect `working-directory`

.github/workflows/test-future.yml, CHANGES.rst, setup.cfg
Dropping use of `distutils` which wasn't explicitly required anyway, but came in through `pip`.
=> Use packaging.version.Version in test-future.yml

.github/workflows/pylint.yml, .github/workflows/pyupgrade.yml, .github/workflows/test-working-directory.yml, CHANGES.rst, README.rst, constraints-future.txt, mypy.ini, pyproject.toml, setup.cfg, src/darker/__main__.py, src/darker/formatters/base_formatter.py, src/darker/formatters/black_formatter.py, src/darker/formatters/none_formatter.py, src/darker/formatters/pyupgrade_config.py, src/darker/formatters/pyupgrade_formatter.py, src/darker/formatters/pyupgrade_wrapper.py, src/darker/formatters/ruff_formatter.py, stubs/pyupgrade/_data.pyi, stubs/pyupgrade/_main.pyi
=> Pyupgrade formatter plugin

CHANGES.rst, setup.py, src/darker/files.py, src/darker/formatters/base_formatter.py, src/darker/formatters/black_formatter.py, src/darker/formatters/formatter_config.py, src/darker/formatters/none_formatter.py, src/darker/formatters/ruff_formatter.py
Possible since Python 3.9. Pylint started to complain about `typing.Pattern`.
**Note:** The `working-directory` [test failure](https://github.com/akaihola/darker/actions/runs/13079611210/job/36499907495?pr=813) can be ignored, it will be fixed in #812.
=> Use `re.Pattern` for type checking

.github/workflows/python-package.yml, .github/workflows/test-working-directory.yml, CHANGES.rst
=> Use newest v4 upload/download artifacts action

CHANGES.rst, src/darker/__main__.py
Python 3.12 emits deprecation warning when using darker
```
DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version.
```
=> Fix python 3.12 deprecation warning

src/darker/verification.py
Use built in dict type instead of typing Dict
=> Update verification.py per pyupgrade parsing

.gitignore, CHANGES.rst, pyproject.toml, setup.cfg, src/darker/__main__.py, src/darker/import_sorting.py, src/darker/tests/test_import_sorting.py, src/darker/tests/test_main_isort.py
=> Respect isort's `skip_glob` setting
