.travis.yml, src/darker/black_diff.py
Run doctests in Travis CI. Fix one doctest which wasn't up-to-date with recent changes.
=> Enable and fix doctests

README.rst
=> Document how to enable darker instead of black in vscode.

CHANGES.rst, pytest.ini, setup.cfg, src/darker/linting.py, src/darker/tests/test_diff.py, src/darker/verification.py
Also made sure the code currently passes Flake8 inspections.
=> Darker source code verifiable with Flake8

README.rst
This pull request for the rebased `vim` branch supersedes #61.
=> Add info for vim in readme.

src/darker/git.py
This is in preparation for supporting commit ranges and latest common ancestors better. This helper class will be used in #80.
=> Add `RevisionRange` class

.pre-commit-config.yaml, CHANGES.rst
**Note:** #107 will fix the build failure.
=> Configure pre commit hooks for Darker itself

CHANGES.rst, mypy.ini, src/darker/__main__.py, src/darker/command_line.py, src/darker/help.py, src/darker/tests/test_command_line.py
This should satisfy sourcery.ai – `make_argument_parser()` is its top recommendation for improving code quality.
=> Move help texts to a separate module

.github/workflows/python-package.yml
Also changing the config so that the CI runs for all PRs, if that is ok for you.
=> Run CI on Windows

setup.cfg, src/darker/__main__.py, src/darker/linting.py, src/darker/tests/test_command_line.py, src/darker/tests/test_linting.py, src/darker/tests/test_main.py, src/darker/tests/test_utils.py
=> Return 1 also for linting errors

CHANGES.rst, src/darker/version.py
=> Release version 1.2.3

CHANGES.rst, setup.cfg
Install `types-toml` for `toml` library stubs.
=> Upgrade to MyPy 0.910 in the test suite

README.rst
#116 Already added a fallback feature, but README didn't release version to reflect it.
I copied pre-commit conf from README and spend an hour figuring out why it's not working. I hope no-one wastes more time anymore. :)
=> Update README.txt to reflect improvement from #116

CHANGES.rst, README.rst
=> Conda instructions

CHANGES.rst, CONTRIBUTORS.rst, README.rst, src/darker/__main__.py, src/darker/black_diff.py, src/darker/command_line.py, src/darker/help.py, src/darker/tests/test_black_diff.py, src/darker/tests/test_command_line.py
Implements https://github.com/akaihola/darker/issues/152
=> Add skip-magic-trailing-comma option to darker and pass it on to black.

README.rst, src/darker/argparse_helpers.py, src/darker/command_line.py, src/darker/help.py
rST has built in support for option lists, maybe we should use it?
=> Rely on rST option list support

CHANGES.rst, src/darker/__main__.py, src/darker/exceptions.py, src/darker/help.py, src/darker/import_sorting.py, src/darker/tests/test_command_line.py, src/darker/tests/test_main.py
=> Shorter and more user friendly import errors

CHANGES.rst, README.rst
This is a possible upcoming feature in Black.
=> Mention Black's possible upcoming line range formatting support in README

CHANGES.rst, Dockerfile, README.rst, action.yml, action/conftest.py, action/main.py
Copying what `psf/black` did and adapted it to Darker.
=> Add a GitHub action

CHANGES.rst, src/darker/tests/test_highlighting.py
=> Fix tests for Pygments 2.11.2

.github/workflows/python-package.yml, default.nix
This is an attempt to do Python 3.10 builds using the Nix package manager on Ubuntu and macos.
=> Build with Nix on Ubuntu and macos

CHANGES.rst, README.rst
=> Document `isort` same-env requirement

README.rst
=> Mention in the `README`: `pytest-darker`, IDEs and `pre-commit`

.github/workflows/python-package.yml, pytest.ini
I extracted these changes from #179 (`--jobs argument`) since it seems merging that one is still getting delayed.
=> Skip linting in certain CI configurations

.bandit.code.yaml, .github/workflows/bandit.yml, .github/workflows/yaml-lint.yml, CHANGES.rst, README.rst, action.yml, action/main.py, action/test_main.py, action/tests/test_main.py, mypy.ini, pyproject.toml
Fixes #281.
Follow-up issue #337 will allow pinning linter packages.
=> GitHub Action options to invoke linters through Darker

src/darker/linting.py
=> Show linter invocation in debug level log

CHANGES.rst, src/darker/__main__.py, src/darker/config.py, src/darker/import_sorting.py, src/darker/tests/test_command_line.py, src/darker/tests/test_import_sorting.py, src/darker/tests/test_main.py, src/darker/utils.py
This is in preparation for flynt support (#266 & #308).
Based on #376, merge that one before this PR.
=> Refactor Black and isort file exclusions into one data structure

.github/actions/commit-range/action.yml, .github/workflows/python-package.yml
=> Replace `set-output` by using the `$GITHUB_OUTPUT` environment file

README.rst
=> Fine-tune README section on PyCharm integration

CHANGES.rst, CONTRIBUTING.rst
=> Document development environment setup

CHANGES.rst, release_tools/bump_version.py
=> Fix `test-bump-version` workflow in a release branch

action/main.py
Fixes [the issue @foxwhite25 pointed out](akaihola/darker/pull/430#discussion_r1058028157) in #430.
=> Bugfix to GitHub Action implementation

setup.py, src/darker/__main__.py, src/darker/tests/test_main.py
Suggested by recent Flake8 versions.
=> Use `!r` for quotes in format strings

CHANGES.rst, README.rst, src/darker/help.py
=> Explain configuration of reformatter/linter tools in README and in `--help`

.github/workflows/isort.yml, .github/workflows/mypy.yml, .github/workflows/pylint.yml, .github/workflows/python-package.yml, .github/workflows/pyupgrade.yml, .github/workflows/safety.yml, .github/workflows/test-bump-version.yml, .github/workflows/test-future.yml, README.rst
This fixes the Node.js 16 deprecation warning.
=> Update to `actions/setup-python@v5`

.github/workflows/python-package.yml, CHANGES.rst, setup.cfg
=> Limit Black below version 24.2 until incompatibility is resolved

.github/workflows/pyupgrade.yml, action/tests/test_main.py, release_tools/bump_version.py, release_tools/update_contributors.py, setup.cfg, src/darker/black_diff.py, src/darker/config.py, src/darker/git.py, src/darker/import_sorting.py, src/darker/linting.py, src/darker/tests/conftest.py, src/darker/utils.py
Follow on from #537. Fixes #448.
=> Drop support for EOL Python 3.7

README.rst
Addresses [this comment](/akaihola/darker/discussions/529#discussioncomment-8828472) in discussion #529.
=> Update "How does it work?" and explain limitations in README

CHANGES.rst
Also fix a couple of typos/duplicates.
=> Add an "Internal" section to change log entries

.github/workflows/python-package.yml, pyproject.toml
=> Restore `[color]` extras

README.rst, release_tools/bump-version-patterns.yaml
Also improve the version bump patterns.
=> Bump remaining version number references to `3.0.0` in `README.rst`
